server:
  port: 8081

spring:
  application:
      name: product
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: sboot
    password: sboot
    url: jdbc:mysql://localhost/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=PRC
  jpa:
    show-sql: true
  zipkin:
      base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG
